# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-28 23:35
from __future__ import unicode_literals

import activflow.tests.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnalysisDiagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('execution_time', models.IntegerField(verbose_name='ExecutionTime')),
                ('assay_type', models.CharField(max_length=50, verbose_name='Assay Type')),
                ('conformant', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=30, verbose_name='Conformant')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('sample_id', models.CharField(max_length=200, validators=[activflow.tests.validators.validate_initial_cap], verbose_name='Sample Id:')),
                ('internal_sample_id', models.UUIDField(default=uuid.uuid4)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepDiagInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified_step_name', models.CharField(max_length=50, verbose_name='QualifiedStepName')),
                ('intermediate_values', models.CharField(max_length=50, verbose_name='IntermediateValues')),
                ('output_values', models.CharField(max_length=50, verbose_name='OutputValues')),
                ('input_values', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.DataValue')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosticdata',
            name='results',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.StepDiagInformation'),
        ),
    ]
